services:
  mongodb:
    image: mongo:8
    container_name: hospital-management-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: hospital_management
    volumes:
      - hospital_mongodb_data:/data/db

volumes:
  hospital_mongodb_data:
